### Vectorization: It is the process of converting text data into numeric data so that future data analysis and machine learning techniques can be applied.

<b>Techniques</b>:<br>
    
1. <b>Word Counts</b><br>
2. <b>TF-IDF</b><br>
3. <b>Embeddings</b>

## Count Vectorizer(Word Counts)

In [22]:
import pandas as pd
import numpy as np

pd.set_option('display.max_colwidth',None)
data = [
    "The product is AMAZING!! 😍 I absolutely love it.",
    "I ordered 2 bottles for $15 from Amazon.",
    "This phone case looks good, but the quality is terrible...",
    "WOW!!! Best purchase I've made this year 🔥🔥",
    "The delivery took 5 days, which was okay.",
    "I don't like this product — it's too expensive!",
    "Battery life is great, but the camera isn't that good.",
    "I've been using this for 3 months & it's still working perfectly.[GREAT PRODUCT]",
    "Worst experience ever!!! 😡 The product arrived damaged.",
    "Can someone tell me if this is compatible with iPhone 15?",
    "The headphones are REALLY good!!! Sound quality = 10/10 🎧",
    "I bought it yesterday... let's see how long it lasts.",
    "Not bad, not great. It's just OK.",
    "The seller sent the wrong color (Black instead of Blue).",
    "My sister LOVES this product, but I personally don't.",
]

data2 = [
    "When life gives you lemons, make lemonade! 🙂",
    "She bought 2 lemons for $1 at Maven Market.",
    "A dozen lemons will make a gallon of lemonade. [AllRecipes]",
    "lemon, lemon, lemons, lemon, lemon, lemons",
    "He's running to the market to get a lemon — there's a great sale today.",
    "iced tea is my favorite",
    "I didn't like the taste of that lemonade at all.",
    "My lemons went bad before I could use them, unfortunately.",
]

df2=pd.DataFrame(data2,columns=['Text'])
df=pd.DataFrame(data,columns=['Customer_Review'])

df

                                                                     Customer_Review
0                                   The product is AMAZING!! 😍 I absolutely love it.
1                                           I ordered 2 bottles for $15 from Amazon.
2                         This phone case looks good, but the quality is terrible...
3                                        WOW!!! Best purchase I've made this year 🔥🔥
4                                          The delivery took 5 days, which was okay.
5                                    I don't like this product — it's too expensive!
6                             Battery life is great, but the camera isn't that good.
7   I've been using this for 3 months & it's still working perfectly.[GREAT PRODUCT]
8                            Worst experience ever!!! 😡 The product arrived damaged.
9                          Can someone tell me if this is compatible with iPhone 15?
10                         The headphones are REALLY good!!! Sound quality = 10/10 🎧
11                             I bought it yesterday... let's see how long it lasts.
12                                                 Not bad, not great. It's just OK.
13                          The seller sent the wrong color (Black instead of Blue).
14                             My sister LOVES this product, but I personally don't.

In [23]:
from defined_nlp_functions import nlp_pipeline

df['Customer_Review']=nlp_pipeline(df['Customer_Review'])
df['Customer_Review']

0           product smiling_face_with_heart eye love
1                           order 2 bottle 15 amazon
2                            phone case look quality
3                             purchase year firefire
4                                delivery take 5 day
5                                            product
6                                battery life camera
7                            ve 3 month work product
8     experience enraged_face product arrive damaged
9                                     tell iphone 15
10                  headphone quality 1010 headphone
11                            buy yesterday let last
12
13                           seller send color black
14                               sister love product
Name: Customer_Review, dtype: object

In [24]:
from sklearn.feature_extraction.text import CountVectorizer


# ---> ngram_range : It decides how many consecutive words (tokens) should be considered together.
    
## ngram_range=(1, 1): Means unigrams — individual words:

# "I love machine learning"

# → I
# → love
# → machine
# → learning

## ngram_range=(1, 2): Means unigrams + bigrams:

# I
# love
# machine
# learning
# I love
# love machine
# machine learning

## ngram_range=(1, 3): Means unigrams + bigrams + trigrams


# ---> min_df means minimum document frequency:  It removes words that occur in very few documents.A word must present at least {value} documents in the vocabulary.

cv=CountVectorizer(stop_words='english',ngram_range=(1,2),min_df=1)


dtm=cv.fit_transform(df['Customer_Review'])


dtm_df=pd.DataFrame(dtm.toarray(),columns=cv.get_feature_names_out())
dtm_df

,1010,1010 headphone,15,15 amazon,amazon,arrive,arrive damaged,battery,battery life,black,...,tell,tell iphone,ve,ve month,work,work product,year,year firefire,yesterday,yesterday let
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,1,0,0,0,0
8,0,0,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,1,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
10,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
nlp_pipeline(df2['Text'])

0    life give lemon lemonade slightly_smiling_face
1                        buy 2 lemon 1 maven market
2             dozen lemon gallon lemonade allrecipe
3               lemon lemon lemon lemon lemon lemon
4                     run market lemon s sale today
5                                  ice tea favorite
6                                    taste lemonade
7                                      lemon go use
Name: Text, dtype: object

In [28]:
cv2=CountVectorizer(stop_words='english',ngram_range=(1,2),min_df=2)

dtm2=cv2.fit_transform(df2['Text'])
dtm2_df=pd.DataFrame(dtm2.toarray(),columns=cv2.get_feature_names_out())

dtm2_df

   lemon  lemonade  lemons  lemons make  make  market
0      0         1       1            1     1       0
1      0         0       1            0     0       1
2      0         1       1            1     1       0
3      4         0       2            0     0       0
4      1         0       0            0     0       1
5      0         0       0            0     0       0
6      0         1       0            0     0       0
7      0         0       1            0     0       0

## TF-IDF Vectorizer: It emphasizes important words by reducing the impact of common words.

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer(stop_words='english',ngram_range=(1,2),min_df=2)
dtm3=tfidf.fit_transform(df2['Text'])

dtm3_df=pd.DataFrame(dtm3.toarray(),columns=tfidf.get_feature_names_out())
dtm3_df

      lemon  lemonade    lemons  lemons make      make    market
0  0.000000  0.482904  0.374782     0.559617  0.559617  0.000000
1  0.000000  0.000000  0.556451     0.000000  0.000000  0.830881
2  0.000000  0.482904  0.374782     0.559617  0.559617  0.000000
3  0.948249  0.000000  0.317527     0.000000  0.000000  0.000000
4  0.707107  0.000000  0.000000     0.000000  0.000000  0.707107
5  0.000000  0.000000  0.000000     0.000000  0.000000  0.000000
6  0.000000  1.000000  0.000000     0.000000  0.000000  0.000000
7  0.000000  0.000000  1.000000     0.000000  0.000000  0.000000