# NLP with Machine Learning

## 1. Sentiment Analysis

#### ->  It is used to determine the positivity and negativity of the text<br>
#### -> An overall sentiment score between -1 and +1 is given to each block of text.<br>
#### -> Sentiment Analysis is applied on raw text.

In [120]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

pd.set_option('display.max_colwidth',None)
data = [
    "The product is AMAZING!! 😍 I absolutely love it.",
    "I ordered 2 bottles for $15 from Amazon.",
    "This phone case looks good, but the quality is terrible...",
    "WOW!!! Best purchase I've made this year 🔥🔥",
    "The delivery took 5 days, which was okay.",
    "I don't like this product — it's too expensive!",
    "Battery life is great, but the camera isn't that good.",
    "I've been using this for 3 months & it's still working perfectly.[GREAT PRODUCT]",
    "Worst experience ever!!! 😡 The product arrived damaged.",
    "Can someone tell me if this is compatible with iPhone 15?",
    "The headphones are REALLY good!!! Sound quality = 10/10 🎧",
    "I bought it yesterday... let's see how long it lasts.",
    "Not bad, not great. It's just OK.",
    "The seller sent the wrong color (Black instead of Blue).",
    "My sister LOVES this product, but I personally don't.",
]

df=pd.DataFrame(data,columns=['Customer_Review'])
df

                                                                     Customer_Review
0                                   The product is AMAZING!! 😍 I absolutely love it.
1                                           I ordered 2 bottles for $15 from Amazon.
2                         This phone case looks good, but the quality is terrible...
3                                        WOW!!! Best purchase I've made this year 🔥🔥
4                                          The delivery took 5 days, which was okay.
5                                    I don't like this product — it's too expensive!
6                             Battery life is great, but the camera isn't that good.
7   I've been using this for 3 months & it's still working perfectly.[GREAT PRODUCT]
8                            Worst experience ever!!! 😡 The product arrived damaged.
9                          Can someone tell me if this is compatible with iPhone 15?
10                         The headphones are REALLY good!!! Sound quality = 10/10 🎧
11                             I bought it yesterday... let's see how long it lasts.
12                                                 Not bad, not great. It's just OK.
13                          The seller sent the wrong color (Black instead of Blue).
14                             My sister LOVES this product, but I personally don't.

In [121]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Example text

text='When life gives you lemons, make lemonade!😊'

analyzer=SentimentIntensityAnalyzer()
analyzer.polarity_scores(text)

# compound is the overall sentiment score which here is positive.

{'neg': 0.0, 'neu': 0.614, 'pos': 0.386, 'compound': 0.7424}

In [122]:
# Applying on dataframe

df['Sentiment Score']=(df['Customer_Review'].apply(lambda x: analyzer.polarity_scores(x)['compound']))
df

,Customer_Review,Sentiment Score
0,The product is AMAZING!! 😍 I absolutely love it.,0.9275
1,I ordered 2 bottles for $15 from Amazon.,0.1779
2,"This phone case looks good, but the quality is terrible...",-0.4939
3,WOW!!! Best purchase I've made this year 🔥🔥,0.7788
4,"The delivery took 5 days, which was okay.",0.2263
5,I don't like this product — it's too expensive!,-0.3404
6,"Battery life is great, but the camera isn't that good.",-0.1429
7,I've been using this for 3 months & it's still working perfectly.[GREAT PRODUCT],0.0000
8,Worst experience ever!!! 😡 The product arrived damaged.,-0.8349
9,Can someone tell me if this is compatible with iPhone 15?,0.0000
10,The headphones are REALLY good!!! Sound quality = 10/10 🎧,0.7005
11,I bought it yesterday... let's see how long it lasts.,0.0000
12,"Not bad, not great. It's just OK.",0.6754
13,The seller sent the wrong color (Black instead of Blue).,-0.4767
14,"My sister LOVES this product, but I personally don't.",0.4052